# URL del foglio Google Sheets
sheet_url = "https://docs.google.com/spreadsheets/d/18wd1gRRq9FNVr9wTm6OGzUMoFCP-oe1JNNqvz7-89Tk/edit?gid=427999749#gid=427999749"

# Credenziali Service Account Google
[gcp_service_account]
type = "service_account"
project_id = "dashboard-aziendale"
private_key_id = "a732289e431317f1b632a4d5ebc231d4b2d00f08"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDs2c/xfEfrrC/C
fnHOZEh8h9lZmX0OgW08e1fMRUejg2RXi7+kVE9yPa/WiMtKmoBo9UJm8UvxR9sK
ex3d/jUmwR/dTZ7Vr15za2zef6SIHYPV8iz/vtcM8G8b3V+NAkIwGf9MgVDm0jrz
haD1aCW428D+qB3CbwiudY/CzwWa/ajKwaPaNBdYl3pwQZ87qZ5jAIB3OzBi2WTA
2ViFEUmUXXazXEnqLwSj6/PN0pmGOGxMnyT1vBkE64da5Insmf72E+bAFXa/HFbs
CisqWhbclITAFiyYo+uTqSj+dMUfj4QA3u2U08i0bMZK0gUPNehzxO5oPnEDIFwv
uEboWA49AgMBAAECggEAEzUfvK7uOzHBxsVPz+PIkBbJPM+qeVpsJCdBib6FjoBZ
ixL5dedjcPmJML3ztIdeigR3v9bqKHVCEXHGDIpwv4WSYrVIf/5Ci9wmnk2eJ26z
Ug6bcRsGIBXAgPM9LDeGbBWzoz3qdGmQn86SrMwnIPxrRIuYLDwqaVF92NfGldi7
3TVAco6o7x1ACZk7Jzs+8a3g9af7RyOBegqANbJqFzL33oUZ9tKo5XK4a6EZOnzA
rhhSQyEcVd8fcoXJjjFizBXw5kiColM/XCVze4xrNYBOFakw+xGdhG818ORvUBNU
16CFRXcGxZ12Z23uJMEvjK3VkW+rMqofV+gwMnPuQQKBgQD68jdzi31LK8W72NA5
/+LO7Lwi76Iyfyd0pQLlANaNza4aQsrQ47y20K4w7ssSCt+scc2zewZfC1ieX8oS
pVRIgNtA2AHTEk+d3IbH+hTI3srrpeca5S3MBGWgun/ldV9alZLSXgz5WGbhFwra
Gly30f1misyqlzJ5KirhGbwV/QKBgQDxnuzs3qJmHkmv6F0wXwESrw2tFtbtPd0X
OxZxMeeU+8ZxNnFxIRn3NtWtRnHg7OQmsDnFB2DL1X+H//4/c+09rayvYoL7uMBD
OR2Bm0fCxzNbwx6HWbhZk0yFhuddYeGaoKlsoV6lztHccN/1a8hy9BqVkVoYGSMs
DgQsr20tQQKBgHKxO5jKmwQ9SE1XhavMgNv0JPSOs4ICzYSpWk5R+L2s0LLd7hZU
z856R/LDYPqpD5ugE9TBGKNd6y3PN+sXtxLAGfVkBEl06ACNZuiFKvS3puTW2W5Y
ansBU3WHZ6b24xLio80UATgBKFweDO6r985n4jn4nBwnqIDqPdjNy0H9AoGBAOsV
icddRfy9c0xndGPfy5d2IoRKOItTKY20u70epQdbgFQeeHltj2nsPDH+3EXPtpu9
0jdVWmR4MUENXT43eJgOJnnuCysHMmk1ZPP5NPTaA6pASa+/J5JfspAoFWvSFELy
FmXPC9ufQqiMWhra54iQ4Fyts07HBmWSrZUcickBAoGAKZynq41jpGxU8kBdtDlD
uK5zWJcADGB5evjAm/2vN4xdqeUipxqS3mL/vs6/JQY51ttKQ5l/tRNw+nNQ++++
Rx2E1hyoa2VxJko8czvnI3ttUUHtS3I3nWzwzgDalYmV1XdYHtdGJZO+eiddix9B
1hkMtvTAqSQ++9FbZpFlo4o=
-----END PRIVATE KEY-----"""
client_email = "dashboard-streamlit@dashboard-aziendale.iam.gserviceaccount.com"
client_id = "100926064432252133017"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dashboard-streamlit%40dashboard-aziendale.iam.gserviceaccount.com"
universe_domain = "googleapis.com"